### ISSUE TITLE
api.get_comments text attr no longer correct

### ISSUE THREAD

**Issue by smalljaguar** [vluzko/manifoldpy#127]
`[x.text for x in manifoldpy.api.get_comments(marketSlug="will-this-market-have-over-50-comme")]` returns a list of `NOTHING`
changing text for content in the definition of Comment works as a hack.

**Comment by smalljaguar** [comment]
`content = [x.content["content"][0]["content"] for x in manifoldpy.api.get_comments(marketSlug="will-this-market-have-over-50-comme")]` works for getting structured comment content
If you only want text, it can be flattened with `flat_list = [item.get("text") for sublist in content for item in sublist]`

**Comment by vluzko** [comment]
Thank you for the report - I will look into this tonight.

**Comment by vluzko** [comment]
Fixed and bumped version.
