### ISSUE TITLE
BOUNTIED_QUESTION isn't a known market outcome type

### ISSUE THREAD

**Issue by RomanHauksson** [vluzko/manifoldpy#151]
```python
from manifoldpy import api
markets = api.get_all_markets()
```

After fetching 53858 markets, this returns the following error:

`ValueError: BOUNTIED_QUESTION isn't a known market outcome type. Submit a bug report if the json came from the API.`

**Comment by vluzko** [comment]
Thank you for the report, looks like the API has been updated. I'll fix this ASAP.
