### ISSUE TITLE
ValueError: POLL isn't a known market outcome type

### ISSUE THREAD

**Issue by 8ball030** [vluzko/manifoldpy#152]
File "/home/tom/.cache/pypoetry/virtualenvs/manifold-a1zt55bt-py3.10/lib/python3.10/site-packages/manifoldpy/api.py", line 283, in from_json
    raise ValueError(
ValueError: POLL isn't a known market outcome type. Submit a bug report if the json came from the API.

this is when running get markets;

```
from manifoldpy import api
markets = api.get_all_markets()

```

**Comment by jagilley** [comment]
Am getting the same. Should be quite fixable, may work on this

**Comment by 8ball030** [comment]
I have it fixed on a local branch I'll push it up later tonight :)
Would you be able to do a release for me this weekend? 
I'd love to use the main lib in my Hackathon entry

**Comment by vluzko** [comment]
I was on vacation this weekend, apologies. Thanks for the report, should be an easy fix.
